services:
  app:
    env_file:
      - .env.production
    build: .
    container_name: vieclam365
    ports:
      - '8888:8888'
    restart: unless-stopped

volumes:
  postgresql-data:
  redis-data:
