services:
  app:
    env_file:
      - .env.production
    build: .
    container_name: vieclam365
    restart: unless-stopped
    networks:
      - cloudflared
    expose:
      - '8888'
networks:
  cloudflared:
    external: true
    name: cloudflared
